version: "2.3"
services:
  demo-container-db:
    image: postgres:12
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - "5442:5432"
    networks:
    - turreta_network
    volumes:
    - db-data:/var/lib/postgresql/data
  demo-pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - "8889:80"
    networks:
    - turreta_network
networks:
  turreta_network:
    driver: bridge
 
volumes:
  db-data:
  
  Hari
